### ISSUE TITLE
Bug Thread

### ISSUE THREAD

**Issue by FrostBite5** [FrostBite5/frostbite-ceg#12]
# The Bug Report Thread
yeah that

**Comment by CatsAreFluffy** [comment]
The entire Issues system is for bug reporting.

**Comment by aarextiaokhiao** [comment]
Yes, does FrostBite5 need to?

**Comment by CatsAreFluffy** [comment]
Someone close this

**Comment by aarextiaokhiao** [comment]
I'm not closing it. Its good idea.

**Comment by CatsAreFluffy** [comment]
It's a terrible idea and a dumb misuse of the Issues system.

**Comment by merp101** [comment]
This is true, because you're supposed to create a separate thing for each bug
eh
