### ISSUE TITLE
Unable to visually purchase two upgrades

### ISSUE THREAD

**Issue by 3ICE** [FrostBite5/frostbite-ceg#77]
Hi,

They are:
```
Included Mic & Maximum RAM: 100,000x faster computers
Cost: 1.00e50
```
and
```
Quantum.: 1,000,000x faster computers.
Cost: 1.00e65
```
also known as `upg20button`, and `upg21button`, respectively.

Won't turn green after click, even though I can afford them both:
```
You have 3.77e83 errors.
You are making 9.67e80 errors per second.
```

Nothing visible happens when clicking the upgrade buttons. No message is printed to the console either.

I have so much money I probably won't even notice if the 1 million times speed kicks in.

Some more digging around in the source code follows:

I base64 decoded my save, here is one key from it:
`"upgrades":[1,2,3,17,18,19,20,21,4,5,6,7,8,15,16,9]`

This means I do have them after all, but the `boughtUpgrade` class is not being applied to the buttons `upg20button` and `upg21button` correctly.

Fix:
Line 480: `	  for (i=17;i<20;i++) {`
should go all the way to 22 instead of just 20.

#12 

Sincerely,
Daniel "3ICE" Berezvai

p.s.: Great game, well done.

**Comment by FrostBite5** [comment]
Thanks for this. I knew about the bug beforehand just not the cause. The upgrades do work, they just do not work in such a way that they display visually. also thanks for the feedback!
